name: Add build assets to release

on:
  release:
    types: [published]

jobs:
  publish-dist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Package distribution
        run: cd dist; for i in */; do zip -0 -r "${i%/}.zip" "$i" & done; wait

      - name: Create Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*.zip
